# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170403_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='basic_information',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exchange_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_having_exchange_currency', to='web.Currency'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_having_home_currency', to='web.Currency'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='radius',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(null=True, upload_to='uploads/profile_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_having_language', to='web.Language'),
        ),
    ]
