# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170405_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
