# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170407_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='uploads/profile_photos/'),
        ),
    ]
