# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170407_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
