# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-10 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170410_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
