# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_feedback_user_responded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerstatus',
            name='description',
        ),
        migrations.AlterField(
            model_name='currency',
            name='postfix',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='currency',
            name='prefix',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='offerstatus',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='basic_information',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
