# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20170427_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='basic_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
